spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
