spring:
  jpa:
    hibernate:
      ddlAuto: update

  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: bitclave

server:
  port: 8080

hybrid:
  nodeUrl: http://localhost:9545/
  ownerPrivateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501200'

  contracts:
    dnsAddress: '0x0'

    account:
      address: '0x0f5ea0a652e851678ebf77b69484bfcd31f9459b'
      gasPrice: '8000000'
      gasLimit: '8000000'

    clientData:
      address: '0xec8be1a5630364292e56d01129e8ee8a9578d7d8'
      gasPrice: '8000000'
      gasLimit: '8000000'

    requestData:
      address: '0x85a84691547b7ccf19d7c31977a7f8c0af1fb25a'
      gasPrice: '8000000'
      gasLimit: '8000000'

    storage:
      address: '0x0'
      gasPrice: '8000000'
      gasLimit: '8000000'
