spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: bitclave

server:
  port: 8080
