spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: postgres1
    password: bitclave1

ethereum:
  nodeUrl: http://localhost:9545/
